/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CombineGameItem: typeof import('./src/components/home/combineGameItem.vue')['default']
    CombineGameItemLeft: typeof import('./src/components/home/combineGameItemLeft.vue')['default']
    CombineGameItemLeftTwo: typeof import('./src/components/home/combineGameItemLeftTwo.vue')['default']
    CombineGameItemRight: typeof import('./src/components/home/combineGameItemRight.vue')['default']
    CombineGameItemTwo: typeof import('./src/components/home/combineGameItemTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleGameItem: typeof import('./src/components/home/singleGameItem.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/tabbar.vue')['default']
  }
}
